name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v1.1.0
        with:
          version: 13.6.0

      - name: 📂 Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: 📥 Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: 📦 Install dependencies
        run: yarn

      - name: 👚 Lint
        run: yarn lint

      - name: 🏁 Type Check
        run: yarn type-check

      - name: 🔍 Run tests
        run: yarn test-build
